<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN7P4A-0081" name="Default test" tests="1" failures="1" timestamp="5 Jul 2017 14:35:11 GMT" time="220.392" errors="0">
  <testcase name="testRunner" time="220.221" classname="testscripts.LoginScenario.TestForMarineValidLogin">
    <failure type="java.lang.AssertionError" message="Click No for insured contact information is not Clicked.; Click No for insured contact information is not Clicked.; Click No for insured contact information is not Clicked.; Click No for insured contact information is not Clicked.">
      <![CDATA[java.lang.AssertionError: Click No for insured contact information is not Clicked.; Click No for insured contact information is not Clicked.; Click No for insured contact information is not Clicked.; Click No for insured contact information is not Clicked.
	at org.testng.Assert.fail(Assert.java:94)
	at com.cognizant.Craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:105)
	at testscripts.LoginScenario.TestForMarineValidLogin.testRunner(TestForMarineValidLogin.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testRunner -->
</testsuite> <!-- Default test -->
