<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN7P4A-0081" name="Default test" tests="1" failures="1" timestamp="30 Jun 2017 10:24:05 GMT" time="12.699" errors="0">
  <testcase name="testRunner" time="12.528" classname="testscripts.LoginScenario.TestForMarineValidLogin">
    <failure type="com.cognizant.framework.FrameworkException" message="The test case &amp;quot;TestForMarineValidLogin&amp;quot; is not found in the Business Flow sheet!">
      <![CDATA[com.cognizant.framework.FrameworkException: The test case "TestForMarineValidLogin" is not found in the Business Flow sheet!
	at com.cognizant.Craft.DriverScript.initializeBusinessFlow(DriverScript.java:535)
	at com.cognizant.Craft.DriverScript.initializeTestScript(DriverScript.java:520)
	at com.cognizant.Craft.DriverScript.executeCraft(DriverScript.java:154)
	at com.cognizant.Craft.DriverScript.driveTestExecution(DriverScript.java:147)
	at testscripts.LoginScenario.TestForMarineValidLogin.testRunner(TestForMarineValidLogin.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testRunner -->
</testsuite> <!-- Default test -->
